env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - IOS_FRAMEWORK_SCHEME="AdvancedOperation iOS"
    - MACOS_FRAMEWORK_SCHEME="AdvancedOperation macOS"
    - TVOS_FRAMEWORK_SCHEME="AdvancedOperation tvOS"
    - WATCHOS_FRAMEWORK_SCHEME="AdvancedOperation watchOS"
    - IOS_SDK=iphonesimulator13.2
    - MACOS_SDK=macosx10.15
    - TVOS_SDK=appletvsimulator13.2
    - WATCHOS_SDK=watchsimulator6.1
    - XCODE_RUN_TESTS="NO"

matrix:
  include:

 # macOS: Swift Tests, CocoaPods and SwiftLint        
    - os: osx
      osx_image: xcode11.3
      language: objective-c
      before_install:
        #- gem install cocoapods --pre --no-document --quiet
        - brew outdated swiftlint || brew upgrade swiftlint
        - brew tap thii/xcbeautify https://github.com/thii/xcbeautify.git
        - brew install xcbeautify
      before_script:
        - swiftlint --reporter "emoji"  
      script:
        - set -o pipefail
        - swift --version
        - swift test -Xswiftc -target -Xswiftc x86_64-apple-macosx10.13
        #- pod lib lint --verbose

    # iOS 12.1
    - os: osx
      osx_image: xcode11.3
      language: objective-c
      env: 
        - DESTINATION="OS=12.1,name=iPhone X" SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK" XCODE_RUN_TESTS="YES" CODECOV_FLAG="ios"

    # iOS 13.3
    - os: osx
      osx_image: xcode11.3
      language: objective-c
      env: 
        - DESTINATION="OS=13.3,name=iPhone 11" SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK" XCODE_RUN_TESTS="YES" CODECOV_FLAG="ios"

    # #watchOS 5.1
    # - os: osx
    #   osx_image: xcode11.3
    #   language: objective-c
    #   env: 
    #     - DESTINATION="OS=5.1,name=Apple Watch Series 4 - 44mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME" SDK="$WATCHOS_SDK" XCODE_RUN_TESTS="NO" CODECOV_FLAG="watchos"

    #watchOS 6.1.1
    - os: osx
      osx_image: xcode11.3
      language: objective-c
      env: 
        - DESTINATION="OS=6.1.1,name=Apple Watch Series 5 - 44mm" SCHEME="$WATCHOS_FRAMEWORK_SCHEME" SDK="$WATCHOS_SDK" XCODE_RUN_TESTS="NO" CODECOV_FLAG="watchos"
    
    # tvOS 12.1
    - os: osx
      osx_image: xcode11.3
      language: objective-c
      env: 
        - DESTINATION="OS=12.2,name=Apple TV 4K (at 1080p)" SCHEME="$TVOS_FRAMEWORK_SCHEME" SDK="$TVOS_SDK" XCODE_RUN_TESTS="YES" CODECOV_FLAG="tvos"

    # tvOS 13.3
    - os: osx
      osx_image: xcode11.3
      language: objective-c
      env: 
        - DESTINATION="OS=13.3,name=Apple TV 4K (at 1080p)" SCHEME="$TVOS_FRAMEWORK_SCHEME" SDK="$TVOS_SDK" XCODE_RUN_TESTS="YES" CODECOV_FLAG="tvos"

    # macOS
    - os: osx
      osx_image: xcode11.3
      language: objective-c
      env: 
       - DESTINATION="arch=x86_64" SCHEME="$MACOS_FRAMEWORK_SCHEME" SDK="$MACOS_SDK" XCODE_RUN_TESTS="YES" CODECOV_FLAG="macos" 

bundler_args: --without release_phase
script:
  - set -o pipefail  
  - swift --version

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      xcodebuild -version;
      xcodebuild -showsdks;

      if [ "$XCODE_RUN_TESTS" == "YES" ]; then
        #xcodebuild -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=YES ENABLE_TESTABILITY=YES build-for-testing test-without-building | xcpretty;
        NSUnbufferedIO=YES xcodebuild test -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -testPlan "$SCHEME" -parallel-testing-enabled YES -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test 2>&1 | xcbeautify
      else
        xcodebuild -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
      fi
    fi