version: 2
jobs:

  linux_swift_4:
    docker:
      - image: ibmcom/swift-ubuntu:4.0
    steps:
      - checkout
      - run: 
          name: Swift Test
          command: swift test
      - run:
          name: Swift build Release
          command: swift build -c release -Xswiftc -static-stdlib       

  linux_swift_4.0.3:
    docker:
      - image: ibmcom/swift-ubuntu:4.0.3
    steps:
      - checkout
      - run: 
          name: Swift Test
          command: swift test
      - run:
          name: Swift build Release
          command: swift build -c release -Xswiftc -static-stdlib

  linux_swift_dev_snapshot:
    docker:
      - image: ubuntu:14.04
    steps:
      - checkout
      - run: 
          name: Install Dependencies
          command: sudo apt-get install clang libicu-dev libcurl4-openssl-dev wget unzip -y
      - run:
          name: Get Swift snapshot
          command: wget https://swift.org/builds/development/ubuntu1404/swift-DEVELOPMENT-SNAPSHOT-2018-01-15-a/swift-DEVELOPMENT-SNAPSHOT-2018-01-15-a-ubuntu14.04.tar.gz             
      - run: 
          name: Unzip
          command: tar zxf swift-DEVELOPMENT*.tar.gz && rm -rf swift-DEVELOPMENT*.tar.gz
      - run: 
          name: Move
          command: sudo mv swift-DEVELOPMENT* /swift-DEVELOPMENT
      - run: 
          name: Export
          command: echo "export PATH=/swift-DEVELOPMENT/usr/bin:\"\${PATH}\"" >> ~/.bashrc
      - run: 
          name: Finish
          command: source ~/.bashrc 

workflows:
  version: 2
  workflow:
    jobs:
      #- linux_swift_4
      #- linux_swift_4.0.3
      - linux_swift_dev_snapshot.0.3