name: "AdvancedOperation CI"

on:
  schedule:
    - cron:  '* 23  * * *' # At the end of every day
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  info:
    name: Show macOS and Xcode versions
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.4_beta.app/Contents/Developer
    steps:
      - name: stats
        run: |
          sw_vers
          xcodebuild -version
          xcodebuild -showsdks
          xcrun simctl list
          brew -v
          brew list
  macOS:
    name: Test macOS
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.4_beta.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: macOS
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild clean test -project "AdvancedOperation.xcodeproj" -scheme "AdvancedOperation macOS" -destination "platform=macOS" -testPlan "AdvancedOperation macOS" -parallel-testing-enabled NO -configuration Release ENABLE_TESTABILITY=YES | xcpretty -c
  iOS:
    name: Test iOS
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.4_beta.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=13.3,name=iPhone 11 Pro"] #, "OS=12.4,name=iPhone XS", "OS=11.4,name=iPhone X"]
    steps:
      - uses: actions/checkout@v2
      - name: iOS - ${{ matrix.destination }}
        run: |
          set -o pipefail && env NSUnbufferedIO=YES xcodebuild clean test -project "AdvancedOperation.xcodeproj" -scheme "AdvancedOperation iOS" -destination "${{ matrix.destination }}" -testPlan "AdvancedOperation iOS" -parallel-testing-enabled NO -configuration Release -enableCodeCoverage YES | xcpretty -c
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
  tvOS:
    name: Test tvOS
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.4_beta.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=13.3,name=Apple TV 4K"] #, "OS=13.0,name=Apple TV 4K (at 1080p)", "OS=11.4,name=Apple TV 4K"]
    steps:
      - uses: actions/checkout@v2
      - name: tvOS - ${{ matrix.destination }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild clean test -project "AdvancedOperation.xcodeproj" -scheme "AdvancedOperation tvOS" -destination "${{ matrix.destination }}" -testPlan "AdvancedOperation tvOS" -parallel-testing-enabled NO -configuration Release | xcpretty -c
  watchOS:
    name: Build watchOS
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.4_beta.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=6.1.1,name=Apple Watch Series 5 - 44mm"] #, ""OS=5.3,name=Apple Watch Series 4 - 44mm", "OS=4.2,name=Apple Watch Series 3 - 42mm"]
    steps:
      - uses: actions/checkout@v2
      - name: watchOS - ${{ matrix.destination }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild clean build -project "AdvancedOperation.xcodeproj" -scheme "AdvancedOperation watchOS" -destination "${{ matrix.destination }}" | xcpretty -c
  spm:
    name: Test SPM Integration
    runs-on: macOS-latest
    needs: [macOS]
    steps:
      - uses: actions/checkout@v2
      - name: SPM Test
        run: |
          swift --version
          swift test
